"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.userRouter = void 0;
var express_1 = require("express");
var user_controller_1 = require("../controllers/user.controller");
var router = (0, express_1.Router)();
router.get("/", user_controller_1.userController.getList);
router.post("/", user_controller_1.userController.create);
router.delete("/:userId", user_controller_1.userController.delete);
router.get("/:userId", user_controller_1.userController.getUserById);
router.put("/:userId", user_controller_1.userController.updateUser);
exports.userRouter = router;
